import fs from 'fs';
import assert from 'assert';
const src=fs.readFileSync(new URL('../js/mg-ai-service.js', import.meta.url),'utf8');
assert.match(src,/brainMode:'multi-brain-whole-text-first'/);
assert.match(src,/const AI_BRAINS=\[/);
assert.match(src,/label:'Qwen3\.5-2B'/);
assert.match(src,/label:'Gemma 3 1B'/);
assert.match(src,/label:'DeepSeek-R1 Distill Qwen 1\.5B'/);
assert.match(src,/const router=await runAiRouter\(input,direction,services\);/);
assert.match(src,/const memorySuggestions=memoryPhraseCandidates\(input,direction,services\);/);
assert.ok(src.indexOf('const router=await runAiRouter(input,direction,services);') < src.indexOf('const memorySuggestions=memoryPhraseCandidates(input,direction,services);'));
assert.match(src,/memoryStage:'10m-after-brains'/);
assert.doesNotMatch(src,/10M dictionary-first/);
console.log('WHOLE-TEXT PRIMARY ARCHITECTURE: PASS');
